services:
  db_master:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"             
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    volumes:
      - db_master:/var/lib/mysql
  db_node:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    ports:
      - "3307:3306"             
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    volumes:
      - db_node:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db_master
      - db_node
    environment:
      WORDPRESS_DB_HOST: db_master
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
    volumes:
      - wordpress:/var/www/html

volumes:
  db_master:
  wordpress:
  db_node: